/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.doctor;

import Models.AdminLoginCreds;
import UserInterface.admin.CommunityOptionPanel;
import UserInterface.admin.DoctorOptionPanel;
import UserInterface.admin.HospitalOptionPanel;
import UserInterface.admin.PatientOptionPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author A
 */
public class DoctorPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorForm
     */
    JPanel bottomPanel;
    Models.System systemObj;
    public DoctorPanel(JPanel bottomPanel,Models.System systemObj) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.systemObj = systemObj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        drTitleLable = new javax.swing.JLabel();
        userIdField = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        adminID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLEASE LOGIN TO DOCTOR PORTAL");

        drTitleLable.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        drTitleLable.setForeground(new java.awt.Color(255, 255, 255));
        drTitleLable.setText("WELCOME DOCTORS");
        drTitleLable.setToolTipText("");

        userIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdFieldActionPerformed(evt);
            }
        });

        goButton.setText("Login");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        adminID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        adminID.setForeground(new java.awt.Color(255, 255, 255));
        adminID.setText("User ID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(drTitleLable))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1)))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(adminID)
                        .addComponent(passwordField)
                        .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(drTitleLable)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(adminID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(316, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
        
        try{
            AdminLoginCreds adminLoginCreds = new AdminLoginCreds();
            adminLoginCreds.addCreds();

            char [] passwordChars = passwordField.getPassword();
            String password = new String(passwordChars);


            if (adminLoginCreds.authenticate(userIdField.getText(), password)){
                
                
//                NewPatient patientRegistrationScreen = new NewPatient(bottomPanel);
//                bottomPanel.add(patientRegistrationScreen);
//                CardLayout layout = (CardLayout) bottomPanel.getLayout();
//                layout.next(bottomPanel);
//                
                DoctorPatientEncounterPanel encounterHistory = new DoctorPatientEncounterPanel(bottomPanel,systemObj);
                bottomPanel.add(encounterHistory);
                CardLayout layout = (CardLayout) bottomPanel.getLayout();
                layout.next(bottomPanel);

            }

            else{
                throw new IllegalArgumentException("Please provide valid credentials");
 
            }
            
        }
        
        catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Invalid Access Error",JOptionPane.ERROR_MESSAGE);
        }
              
    }//GEN-LAST:event_goButtonActionPerformed

    private void userIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdFieldActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_userIdFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminID;
    private javax.swing.JLabel drTitleLable;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userIdField;
    // End of variables declaration//GEN-END:variables
}
