/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.doctor;

import Models.City;
import Models.Community;
import Models.House;
import Models.Patient;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import javax.swing.JOptionPane;


import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A
 */
public class NewPatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewPatient
     */
    JPanel bottomPanel;
    
    public NewPatientPanel(JPanel bottomPanel) {
        initComponents();
        this.bottomPanel = bottomPanel;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fnLabel2 = new javax.swing.JLabel();
        lnLabel3 = new javax.swing.JLabel();
        IDLabel4 = new javax.swing.JLabel();
        ageLabel5 = new javax.swing.JLabel();
        pnLabel6 = new javax.swing.JLabel();
        emailLabel2 = new javax.swing.JLabel();
        houseLabel3 = new javax.swing.JLabel();
        cityLabel4 = new javax.swing.JLabel();
        communityLabel7 = new javax.swing.JLabel();
        patientFnTextField = new javax.swing.JTextField();
        patientLnTextField = new javax.swing.JTextField();
        patientIDTextField1 = new javax.swing.JTextField();
        patientPnTextField2 = new javax.swing.JTextField();
        patientAgeTextField3 = new javax.swing.JTextField();
        patientEmailTextField1 = new javax.swing.JTextField();
        patientHouseTextField2 = new javax.swing.JTextField();
        patientCityextField3 = new javax.swing.JTextField();
        communityComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        patientTypeLabel = new javax.swing.JLabel();
        patientTypeComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        diagnoseButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROVIDE PATIENT INFORMATION");

        fnLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fnLabel2.setForeground(new java.awt.Color(255, 255, 255));
        fnLabel2.setText("First Name");

        lnLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lnLabel3.setForeground(new java.awt.Color(255, 255, 255));
        lnLabel3.setText("Last Name");

        IDLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        IDLabel4.setForeground(new java.awt.Color(255, 255, 255));
        IDLabel4.setText("ID");

        ageLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ageLabel5.setForeground(new java.awt.Color(255, 255, 255));
        ageLabel5.setText("Age");

        pnLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pnLabel6.setForeground(new java.awt.Color(255, 255, 255));
        pnLabel6.setText("Phone Number");

        emailLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        emailLabel2.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel2.setText("Email");

        houseLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        houseLabel3.setForeground(new java.awt.Color(255, 255, 255));
        houseLabel3.setText("House");

        cityLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cityLabel4.setForeground(new java.awt.Color(255, 255, 255));
        cityLabel4.setText("City");

        communityLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        communityLabel7.setForeground(new java.awt.Color(255, 255, 255));
        communityLabel7.setText("Community");

        patientFnTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientFnTextFieldActionPerformed(evt);
            }
        });

        patientIDTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                patientIDTextField1KeyPressed(evt);
            }
        });

        patientPnTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                patientPnTextField2KeyPressed(evt);
            }
        });

        patientAgeTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                patientAgeTextField3KeyPressed(evt);
            }
        });

        patientEmailTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientEmailTextField1ActionPerformed(evt);
            }
        });

        patientHouseTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientHouseTextField2ActionPerformed(evt);
            }
        });

        patientCityextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientCityextField3ActionPerformed(evt);
            }
        });

        communityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brampton", "Mississauga", "North York", "Oakville" }));
        communityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityComboBoxActionPerformed(evt);
            }
        });

        saveButton.setText("SAVE PATIENT DETAILS");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        patientTypeLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        patientTypeLabel.setForeground(new java.awt.Color(255, 255, 255));
        patientTypeLabel.setText("Patient Type");

        patientTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acute Patient", "Chronic Patient", "Pediatric Patient", "Geriatric Patient", "Emergency Patient", "Surgical Patient", "Psychiatric Patient", "Rehabilitation Patient" }));
        patientTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientTypeComboBoxActionPerformed(evt);
            }
        });

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Firstname", "Lastname", "ID", "Age", "Phone", "Email", "House", "City", "Community", "Patient Type"
            }
        ));
        jScrollPane1.setViewportView(patientTable);

        diagnoseButton.setText("PROVIDE VITAL SIGNS");
        diagnoseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnoseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ageLabel5)
                        .addComponent(fnLabel2)
                        .addComponent(lnLabel3)
                        .addComponent(IDLabel4)
                        .addComponent(patientIDTextField1)
                        .addComponent(patientLnTextField)
                        .addComponent(patientFnTextField)
                        .addComponent(patientAgeTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnLabel6)
                    .addComponent(patientPnTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(communityLabel7)
                            .addComponent(patientTypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(patientHouseTextField2)
                        .addComponent(communityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(patientCityextField3)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailLabel2)
                                .addComponent(houseLabel3)
                                .addComponent(cityLabel4))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(patientTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(patientEmailTextField1)))
                .addGap(132, 132, 132))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(196, 196, 196))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(diagnoseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(fnLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientFnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lnLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientLnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IDLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ageLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientAgeTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(patientPnTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(houseLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientCityextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cityLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(patientHouseTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(communityLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(communityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(patientTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(emailLabel2)))
                        .addGap(12, 12, 12)
                        .addComponent(patientEmailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(diagnoseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientFnTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientFnTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientFnTextFieldActionPerformed

    private void patientEmailTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientEmailTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientEmailTextField1ActionPerformed

    private void patientHouseTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientHouseTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientHouseTextField2ActionPerformed

    private void patientCityextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientCityextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientCityextField3ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        Patient patient = new Patient();
        House house = new House();
        City city = new City("","");
        Community community = new Community();
        patient.setFirstName(patientFnTextField.getText());
        patient.setLastName(patientLnTextField.getText());
        patient.setId(Integer.parseInt(patientIDTextField1.getText()));
        patient.setAge(Integer.parseInt(patientAgeTextField3.getText()));
        patient.setPhone(Long.valueOf(patientPnTextField2.getText()));
        patient.setEmail(patientEmailTextField1.getText());
        
        house.setHouseNumber(Integer.parseInt(patientHouseTextField2.getText()));
        patient.setHouse(house);
        
        city.setCityName(patientCityextField3.getText());
        patient.setCity(city);
       
       

        String communityNameString = communityComboBox.getSelectedItem().toString();
        community.setCommunityName(communityNameString);
        patient.setCommunity(community);
        

        String selectedPatientType = patientTypeComboBox.getSelectedItem().toString();
        patient.setPatientType(selectedPatientType);

        
        populatePatientDetails(patient);
        patientFnTextField.setText("");
        patientLnTextField.setText("");
        patientIDTextField1.setText("");
        patientAgeTextField3.setText("");
        patientPnTextField2.setText("");
        patientEmailTextField1.setText("");
        patientHouseTextField2.setText("");
        patientCityextField3.setText("");
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void communityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_communityComboBoxActionPerformed

    private void patientTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientTypeComboBoxActionPerformed

    private void diagnoseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnoseButtonActionPerformed
        // TODO add your handling code here:
        VitalSignsPanel patientVitalSigns = new VitalSignsPanel(bottomPanel);
        bottomPanel.add(patientVitalSigns);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);
    }//GEN-LAST:event_diagnoseButtonActionPerformed

    private void patientAgeTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientAgeTextField3KeyPressed
        // TODO add your handling code here:
        try{
            
            int age = Integer.parseInt(patientAgeTextField3.getText());
            patientAgeTextField3.setForeground(Color.black);
        } 
        catch(Exception e){
           patientAgeTextField3.setForeground(Color.red);
        }
    }//GEN-LAST:event_patientAgeTextField3KeyPressed

    private void patientIDTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientIDTextField1KeyPressed
        // TODO add your handling code here:
        try{
            
            int id = Integer.parseInt(patientIDTextField1.getText());
            patientIDTextField1.setForeground(Color.black);
        } 
        catch(Exception e){
           patientIDTextField1.setForeground(Color.red);
        }
    }//GEN-LAST:event_patientIDTextField1KeyPressed

    private void patientPnTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientPnTextField2KeyPressed
        // TODO add your handling code here:
        try{
            
            Long id = Long.parseLong(patientPnTextField2.getText());
            patientPnTextField2.setForeground(Color.black);
        } 
        catch(Exception e){
           patientPnTextField2.setForeground(Color.red);
        }
    }//GEN-LAST:event_patientPnTextField2KeyPressed
    private void populatePatientDetails(Patient patient){
        
        String data[] = {patient.getFirstName(),
                         patient.getLastName(),
                         String.valueOf(patient.getId()),
                         String.valueOf(patient.getAge()),
                         patient.getPhone().toString(),
                         patient.getEmail(),
                         String.valueOf(patient.getHouse().getHouseNumber()),
                         patient.getCommunity().getCommunityName(),
                         patient.getCity().getCityName(),
                         patient.getPatientType()};

        DefaultTableModel tblmodel = (DefaultTableModel) patientTable.getModel();

        tblmodel.addRow(data);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDLabel4;
    private javax.swing.JLabel ageLabel5;
    private javax.swing.JLabel cityLabel4;
    private javax.swing.JComboBox<String> communityComboBox;
    private javax.swing.JLabel communityLabel7;
    private javax.swing.JButton diagnoseButton;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JLabel fnLabel2;
    private javax.swing.JLabel houseLabel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lnLabel3;
    private javax.swing.JTextField patientAgeTextField3;
    private javax.swing.JTextField patientCityextField3;
    private javax.swing.JTextField patientEmailTextField1;
    private javax.swing.JTextField patientFnTextField;
    private javax.swing.JTextField patientHouseTextField2;
    private javax.swing.JTextField patientIDTextField1;
    private javax.swing.JTextField patientLnTextField;
    private javax.swing.JTextField patientPnTextField2;
    private javax.swing.JTable patientTable;
    private javax.swing.JComboBox<String> patientTypeComboBox;
    private javax.swing.JLabel patientTypeLabel;
    private javax.swing.JLabel pnLabel6;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
