/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.doctor;

import Models.Patient;
import java.awt.Color;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nosil
 */
public class VitalSignsPanel extends javax.swing.JPanel {

    /**
     * Creates new form VitalSigns
     */
    
    JPanel bottomPanel;
    public VitalSignsPanel(JPanel bottomPanel) {
        initComponents();
        this.bottomPanel = bottomPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pulseTextField4 = new javax.swing.JTextField();
        weightLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        temLabel2 = new javax.swing.JLabel();
        tempTextField = new javax.swing.JTextField();
        bpLabel2 = new javax.swing.JLabel();
        BPTextField2 = new javax.swing.JTextField();
        bgLabel3 = new javax.swing.JLabel();
        weightTextField3 = new javax.swing.JTextField();
        pulseLabel4 = new javax.swing.JLabel();
        BgTextField4 = new javax.swing.JTextField();
        doeLabel2 = new javax.swing.JLabel();
        saveButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(51, 51, 51));

        pulseTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulseTextField4ActionPerformed(evt);
            }
        });

        weightLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        weightLabel5.setForeground(new java.awt.Color(255, 255, 255));
        weightLabel5.setText("Weight");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TAKE VITAL SIGNS");

        temLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        temLabel2.setForeground(new java.awt.Color(255, 255, 255));
        temLabel2.setText("Temperature");

        tempTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempTextFieldActionPerformed(evt);
            }
        });
        tempTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tempTextFieldKeyPressed(evt);
            }
        });

        bpLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bpLabel2.setForeground(new java.awt.Color(255, 255, 255));
        bpLabel2.setText("Blood Pressure");

        BPTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BPTextField2KeyPressed(evt);
            }
        });

        bgLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bgLabel3.setForeground(new java.awt.Color(255, 255, 255));
        bgLabel3.setText("Blood Glucose");

        weightTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                weightTextField3KeyPressed(evt);
            }
        });

        pulseLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pulseLabel4.setForeground(new java.awt.Color(255, 255, 255));
        pulseLabel4.setText("Pulse");

        BgTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BgTextField4KeyPressed(evt);
            }
        });

        doeLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        doeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        doeLabel2.setText("Date of Entry");

        saveButton1.setText("START DIAGNOSIS");
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(doeLabel2)
                            .addComponent(weightLabel5)
                            .addComponent(pulseLabel4)
                            .addComponent(bgLabel3)
                            .addComponent(temLabel2)
                            .addComponent(bpLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                .addComponent(weightTextField3, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BPTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(191, 191, 191)
                            .addComponent(tempTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pulseTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(191, 191, 191)
                            .addComponent(BgTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saveButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(temLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tempTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bpLabel2)
                .addGap(10, 10, 10)
                .addComponent(BPTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bgLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BgTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pulseLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pulseTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(weightLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(weightTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doeLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(saveButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tempTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempTextFieldActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        // TODO add your handling code here:
//        Models.VitalSigns userVitals = new Models.VitalSigns();
//        userVitals.setTemperature(Integer.parseInt(tempTextField.getText()));
//        userVitals.setBloodPressure(BPTextField2.getText());
//        userVitals.setBloodGlucose(Double.parseDouble(BgTextField4.getText()));
//        userVitals.setPulse(Integer.parseInt(pulseTextField4.getText()));
//        userVitals.setWeight(Double.parseDouble(weightTextField3.getText()));
//        userVitals.setDateOfVitalEntry(jDateChooser1.getDate());
        JOptionPane.showMessageDialog(this, "Diagnosis Completed");
        
    }//GEN-LAST:event_saveButton1ActionPerformed

    private void tempTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tempTextFieldKeyPressed
        // TODO add your handling code here:
        try{
            double temp = Double.parseDouble(tempTextField.getText());
            //int temperature = Integer.parseInt(tempTextField.getText());
            tempTextField.setForeground(Color.black);
        } 
        catch(Exception e){
            tempTextField.setForeground(Color.red);
        }
    }//GEN-LAST:event_tempTextFieldKeyPressed

    private void BPTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BPTextField2KeyPressed
        // TODO add your handling code here:
//        try{
//            double temp = Double.parseDouble(BPTextField2.getText());
//            //int temperature = Integer.parseInt(tempTextField.getText());
//            BPTextField2.setForeground(Color.black);
//        } 
//        catch(Exception e){
//            BPTextField2.setForeground(Color.red);
//        }
    }//GEN-LAST:event_BPTextField2KeyPressed

    private void BgTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BgTextField4KeyPressed
        // TODO add your handling code here:
        try{
            double bg = Double.parseDouble(BgTextField4.getText());
            
            BgTextField4.setForeground(Color.black);
        } 
        catch(Exception e){
            BgTextField4.setForeground(Color.red);
        }
    }//GEN-LAST:event_BgTextField4KeyPressed

    private void pulseTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulseTextField4ActionPerformed
        // TODO add your handling code here:
        try{
            
            int pulse = Integer.parseInt(pulseTextField4.getText());
            pulseTextField4.setForeground(Color.black);
        } 
        catch(Exception e){
           pulseTextField4.setForeground(Color.red);
        }
    }//GEN-LAST:event_pulseTextField4ActionPerformed

    private void weightTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_weightTextField3KeyPressed
        // TODO add your handling code here:
        try{
            
            int weight = Integer.parseInt(weightTextField3.getText());
            weightTextField3.setForeground(Color.black);
        } 
        catch(Exception e){
           weightTextField3.setForeground(Color.red);
        }
    }//GEN-LAST:event_weightTextField3KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BPTextField2;
    private javax.swing.JTextField BgTextField4;
    private javax.swing.JLabel bgLabel3;
    private javax.swing.JLabel bpLabel2;
    private javax.swing.JLabel doeLabel2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pulseLabel4;
    private javax.swing.JTextField pulseTextField4;
    private javax.swing.JButton saveButton1;
    private javax.swing.JLabel temLabel2;
    private javax.swing.JTextField tempTextField;
    private javax.swing.JLabel weightLabel5;
    private javax.swing.JTextField weightTextField3;
    // End of variables declaration//GEN-END:variables
}
