/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.admin;

import javax.swing.JPanel;

import Models.AdminLoginCreds;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author yihan
 */
public class AdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form adminScreen
     */
    JPanel bottomPanel;
    public AdminPanel(JPanel bottomPanel) {
        initComponents();
        this.bottomPanel = bottomPanel;
        clearAllFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adminID = new javax.swing.JLabel();
        userIdField = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        adminTypeDropDown = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME ADMINS");

        adminID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        adminID.setForeground(new java.awt.Color(255, 255, 255));
        adminID.setText("User ID");

        userIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdFieldActionPerformed(evt);
            }
        });

        loginBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Select Admin Type");

        adminTypeDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PATIENT", "DOCTOR", "HOSPITAL", "COMMUNITY" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(adminID)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(passwordField)
                                .addComponent(userIdField)
                                .addComponent(adminTypeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(103, 103, 103)
                .addComponent(adminID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminTypeDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        
        try{
            AdminLoginCreds adminLoginCreds = new AdminLoginCreds();
            adminLoginCreds.addCreds();

            char [] passwordChars = passwordField.getPassword();
            String password = new String(passwordChars);


            if (adminLoginCreds.authenticate(userIdField.getText(), password)){
               
                
                switch(adminTypeDropDown.getSelectedItem().toString()){
                
                    case "PATIENT" -> {

                        PatientOptionPanel patientOptionPanel = new PatientOptionPanel(bottomPanel);
                        bottomPanel.add(patientOptionPanel);
                        CardLayout layout = (CardLayout) bottomPanel.getLayout();
                        layout.next(bottomPanel);

                    }

                    case "DOCTOR" -> {

                        DoctorOptionPanel doctorOptionPanel = new DoctorOptionPanel(bottomPanel);
                        bottomPanel.add(doctorOptionPanel);
                        CardLayout layout = (CardLayout) bottomPanel.getLayout();
                        layout.next(bottomPanel);
                    }
                    
                    case "HOSPITAL" -> {
                        
                        
                        HospitalOptionPanel hospitalOptionPanel = new HospitalOptionPanel(bottomPanel);
                        bottomPanel.add(hospitalOptionPanel);
                        CardLayout layout = (CardLayout) bottomPanel.getLayout();
                        layout.next(bottomPanel);
                        
                    }
                    
                    case "COMMUNITY" -> {
                        
                        CommunityOptionPanel communityOptionPanel = new CommunityOptionPanel(bottomPanel);
                        bottomPanel.add(communityOptionPanel);
                        CardLayout layout = (CardLayout) bottomPanel.getLayout();
                        layout.next(bottomPanel);
                        
                    }
                    
                    default -> {
                        
                        throw new IllegalArgumentException("please select correct Admin Type");
                    }
                 
         
            }

            }

            else{
                throw new IllegalArgumentException("Please provide valid credentials");
 
            }
        }
        
        catch(IllegalArgumentException e){
            
            JOptionPane.showMessageDialog(this, e.getMessage(),"Admin Access Error",JOptionPane.ERROR_MESSAGE);
            
        }
       
        
        
    }//GEN-LAST:event_loginBtnActionPerformed
    private void clearAllFields(){
        
        userIdField.setText("");
        passwordField.setText("");
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminID;
    private javax.swing.JComboBox<String> adminTypeDropDown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userIdField;
    // End of variables declaration//GEN-END:variables
}
