/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.admin;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author chait
 */
public class CommunityOptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityOptionPanel
     */
    JPanel bottomPanel;
    public CommunityOptionPanel(JPanel bottomPanel) {
        initComponents();
        this.bottomPanel = bottomPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        communityDetailsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        goToSystemAdminButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();

        communityDetailsButton.setText("GO TO COMMUNITY DETAILS");
        communityDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityDetailsButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("SELECT ONE OPTION FROM BELOW");

        goToSystemAdminButton.setText("GO TO SYSTEM ADMIN");
        goToSystemAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToSystemAdminButtonActionPerformed(evt);
            }
        });

        goBackButton.setText("Go Back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(goToSystemAdminButton)
                .addGap(95, 95, 95)
                .addComponent(communityDetailsButton)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(goBackButton)
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(goBackButton))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(communityDetailsButton)
                    .addComponent(goToSystemAdminButton))
                .addContainerGap(486, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goToSystemAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToSystemAdminButtonActionPerformed
        // TODO add your handling code here:
        
        AdminPanel adminPanel = new AdminPanel(bottomPanel);
        bottomPanel.add(adminPanel);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.previous(bottomPanel);
        
        
    }//GEN-LAST:event_goToSystemAdminButtonActionPerformed

    private void communityDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityDetailsButtonActionPerformed
        // TODO add your handling code here:
        
        
        ExistingCommunityAdminPanel communityAdminPanel = new ExistingCommunityAdminPanel(bottomPanel);
        
        bottomPanel.add(communityAdminPanel);
        
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        
        layout.next(bottomPanel);
    }//GEN-LAST:event_communityDetailsButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        // TODO add your handling code here:

        CommunityOptionPanel communityOptionPanel = new CommunityOptionPanel(bottomPanel);
        bottomPanel.add(communityOptionPanel);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.previous(bottomPanel);
    }//GEN-LAST:event_goBackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton communityDetailsButton;
    private javax.swing.JButton goBackButton;
    private javax.swing.JButton goToSystemAdminButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
