/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

/**
 *
 * @author yihan
 */
public class DoctorModifyPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalModifyPanel
     */
    public DoctorModifyPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addDoctorLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        searchDoctorLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorTable = new javax.swing.JTable();
        searchTextField = new javax.swing.JTextField();
        addDoctorButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        emailLabel = new javax.swing.JLabel();
        houseLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        communityLabel = new javax.swing.JLabel();
        yearofExperienceLabel = new javax.swing.JLabel();
        qualificationLabel = new javax.swing.JLabel();
        specialtyLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        houseTextField = new javax.swing.JTextField();
        communityTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        specialtyTextField = new javax.swing.JTextField();
        yearofExperienceTextField = new javax.swing.JTextField();
        qualificationTextField = new javax.swing.JTextField();
        ageLabel2 = new javax.swing.JLabel();
        lastNameLabel2 = new javax.swing.JLabel();
        phoneLabel2 = new javax.swing.JLabel();
        lastNameField2 = new javax.swing.JTextField();
        emailLabel2 = new javax.swing.JLabel();
        ageTextField2 = new javax.swing.JTextField();
        houseLabel2 = new javax.swing.JLabel();
        phoneTextField2 = new javax.swing.JTextField();
        cityLabel2 = new javax.swing.JLabel();
        firstNameTextField2 = new javax.swing.JTextField();
        communityLabel2 = new javax.swing.JLabel();
        yearofExperienceLabel2 = new javax.swing.JLabel();
        qualificationLabel2 = new javax.swing.JLabel();
        specialtyLabel2 = new javax.swing.JLabel();
        emailTextField2 = new javax.swing.JTextField();
        houseTextField2 = new javax.swing.JTextField();
        communityTextField2 = new javax.swing.JTextField();
        cityTextField2 = new javax.swing.JTextField();
        specialtyTextField2 = new javax.swing.JTextField();
        yearOfExperienceTextField2 = new javax.swing.JTextField();
        uploadButton = new javax.swing.JButton();
        qualificationTextField2 = new javax.swing.JTextField();
        firstNameLabel2 = new javax.swing.JLabel();

        addDoctorLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        addDoctorLabel.setText("Add New Doctor");

        firstNameLabel.setText("First Name");

        ageLabel.setText("Age");

        lastNameLabel.setText("LastName");

        phoneLabel.setText("Phone No.");

        phoneTextField.setPreferredSize(new java.awt.Dimension(100, 23));

        firstNameTextField.setPreferredSize(new java.awt.Dimension(100, 23));

        searchDoctorLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        searchDoctorLabel.setText("Search a Doctor:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 412));

        doctorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Age", "Phone No.", "Email", "House", "Comminity", "City", "Specialty", "YoE", "Qualifications"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        doctorTable.setMinimumSize(new java.awt.Dimension(500, 80));
        doctorTable.setPreferredSize(new java.awt.Dimension(500, 80));
        jScrollPane1.setViewportView(doctorTable);
        if (doctorTable.getColumnModel().getColumnCount() > 0) {
            doctorTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            doctorTable.getColumnModel().getColumn(1).setResizable(false);
            doctorTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            doctorTable.getColumnModel().getColumn(2).setResizable(false);
            doctorTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            doctorTable.getColumnModel().getColumn(3).setResizable(false);
            doctorTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            doctorTable.getColumnModel().getColumn(4).setResizable(false);
            doctorTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            doctorTable.getColumnModel().getColumn(5).setResizable(false);
            doctorTable.getColumnModel().getColumn(5).setPreferredWidth(100);
            doctorTable.getColumnModel().getColumn(6).setResizable(false);
            doctorTable.getColumnModel().getColumn(6).setPreferredWidth(100);
            doctorTable.getColumnModel().getColumn(7).setResizable(false);
            doctorTable.getColumnModel().getColumn(7).setPreferredWidth(100);
            doctorTable.getColumnModel().getColumn(8).setResizable(false);
            doctorTable.getColumnModel().getColumn(8).setPreferredWidth(100);
            doctorTable.getColumnModel().getColumn(9).setResizable(false);
            doctorTable.getColumnModel().getColumn(9).setPreferredWidth(100);
            doctorTable.getColumnModel().getColumn(10).setResizable(false);
            doctorTable.getColumnModel().getColumn(10).setPreferredWidth(100);
        }

        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        addDoctorButton.setText("Add");

        viewButton.setText("View");

        editButton.setText("Edit");

        deleteButton.setText("Delete");

        emailLabel.setText("Email");

        houseLabel.setText("House");

        cityLabel.setText("City");

        communityLabel.setText("Community");

        yearofExperienceLabel.setText("Years of Experience");

        qualificationLabel.setText("Qualifications");

        specialtyLabel.setText("Specialty");

        emailTextField.setPreferredSize(new java.awt.Dimension(100, 23));

        ageLabel2.setText("Age");

        lastNameLabel2.setText("LastName");

        phoneLabel2.setText("Phone No.");

        emailLabel2.setText("Email");

        houseLabel2.setText("House");

        phoneTextField2.setPreferredSize(new java.awt.Dimension(100, 23));

        cityLabel2.setText("City");

        firstNameTextField2.setPreferredSize(new java.awt.Dimension(100, 23));

        communityLabel2.setText("Community");

        yearofExperienceLabel2.setText("Years of Experience");

        qualificationLabel2.setText("Qualifications");

        specialtyLabel2.setText("Specialty");

        emailTextField2.setPreferredSize(new java.awt.Dimension(100, 23));

        houseTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseTextField2ActionPerformed(evt);
            }
        });

        uploadButton.setText("Upload");

        firstNameLabel2.setText("First Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageLabel)
                            .addComponent(phoneLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel)
                            .addComponent(emailLabel))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(lastNameTextField)
                            .addComponent(ageTextField)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(houseLabel)
                            .addComponent(communityLabel)
                            .addComponent(cityLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(houseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(communityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(qualificationLabel)
                                .addGap(56, 56, 56)
                                .addComponent(qualificationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(specialtyLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(specialtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(yearofExperienceLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(yearofExperienceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(addDoctorButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchDoctorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageLabel2)
                            .addComponent(phoneLabel2)
                            .addComponent(lastNameLabel2)
                            .addComponent(firstNameLabel2)
                            .addComponent(emailLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(firstNameTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNameField2)
                            .addComponent(ageTextField2)
                            .addComponent(phoneTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(houseLabel2)
                            .addComponent(communityLabel2)
                            .addComponent(cityLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(houseTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cityTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(communityTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(qualificationLabel2)
                                .addGap(56, 56, 56)
                                .addComponent(qualificationTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(specialtyLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(specialtyTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(yearofExperienceLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(yearOfExperienceTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(uploadButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(viewButton)
                                .addGap(18, 18, 18)
                                .addComponent(editButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(addDoctorLabel)))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addDoctorLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameLabel)
                            .addComponent(specialtyLabel)
                            .addComponent(specialtyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lastNameLabel)
                                .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yearofExperienceLabel))
                            .addComponent(yearofExperienceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(qualificationTextField)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ageLabel)
                                .addComponent(qualificationLabel)
                                .addComponent(cityLabel)
                                .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(phoneLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addDoctorButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(houseLabel)
                            .addComponent(houseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(communityLabel)
                            .addComponent(communityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDoctorLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameLabel2)
                            .addComponent(specialtyLabel2)
                            .addComponent(specialtyTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lastNameLabel2)
                                .addComponent(lastNameField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(yearofExperienceLabel2))
                            .addComponent(yearOfExperienceTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(qualificationTextField2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ageTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ageLabel2)
                                .addComponent(qualificationLabel2)
                                .addComponent(cityLabel2)
                                .addComponent(cityTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(phoneLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(phoneTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel2)
                            .addComponent(emailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uploadButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(houseLabel2)
                            .addComponent(houseTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(communityLabel2)
                            .addComponent(communityTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void houseTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_houseTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDoctorButton;
    private javax.swing.JLabel addDoctorLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageLabel2;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField ageTextField2;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel cityLabel2;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField cityTextField2;
    private javax.swing.JLabel communityLabel;
    private javax.swing.JLabel communityLabel2;
    private javax.swing.JTextField communityTextField;
    private javax.swing.JTextField communityTextField2;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable doctorTable;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField emailTextField2;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JTextField firstNameTextField2;
    private javax.swing.JLabel houseLabel;
    private javax.swing.JLabel houseLabel2;
    private javax.swing.JTextField houseTextField;
    private javax.swing.JTextField houseTextField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameLabel2;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneLabel2;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField phoneTextField2;
    private javax.swing.JLabel qualificationLabel;
    private javax.swing.JLabel qualificationLabel2;
    private javax.swing.JTextField qualificationTextField;
    private javax.swing.JTextField qualificationTextField2;
    private javax.swing.JLabel searchDoctorLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel specialtyLabel;
    private javax.swing.JLabel specialtyLabel2;
    private javax.swing.JTextField specialtyTextField;
    private javax.swing.JTextField specialtyTextField2;
    private javax.swing.JButton uploadButton;
    private javax.swing.JButton viewButton;
    private javax.swing.JTextField yearOfExperienceTextField2;
    private javax.swing.JLabel yearofExperienceLabel;
    private javax.swing.JLabel yearofExperienceLabel2;
    private javax.swing.JTextField yearofExperienceTextField;
    // End of variables declaration//GEN-END:variables
}
