/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.admin;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author chait
 */
public class DoctorOptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    JPanel bottomPanel;
    public DoctorOptionPanel(JPanel bottomPanel) {
        initComponents();
        this.bottomPanel = bottomPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        doctorDetails = new javax.swing.JButton();
        systemAdmin = new javax.swing.JButton();

        jLabel1.setText("SELECT ONE OPTION FROM BELOW");

        doctorDetails.setText("GO TO DOCTOR DETAILS");
        doctorDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorDetailsActionPerformed(evt);
            }
        });

        systemAdmin.setText("GO TO LOGIN ");
        systemAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(systemAdmin)
                        .addGap(113, 113, 113)
                        .addComponent(doctorDetails))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorDetails)
                    .addComponent(systemAdmin))
                .addContainerGap(465, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doctorDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorDetailsActionPerformed
        // TODO add your handling code here:
        
        DoctorAdminPanel doctorAdminPanel = new DoctorAdminPanel(bottomPanel);
        
        bottomPanel.add(doctorAdminPanel);
        
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        
        layout.next(bottomPanel);
    }//GEN-LAST:event_doctorDetailsActionPerformed

    private void systemAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemAdminActionPerformed
        // TODO add your handling code here:

        AdminPanel adminPanel = new AdminPanel(bottomPanel);
        bottomPanel.add(adminPanel);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);
    }//GEN-LAST:event_systemAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doctorDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton systemAdmin;
    // End of variables declaration//GEN-END:variables
}
