/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Patient;

import Models.Hospital;
import Models.DoctorDirectory;
import Models.Doctor;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chait
 */
public class AppointmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form AppointmentPanel
     */
    JPanel bottomPanel;
    Models.Systems rootDataObj;
    Models.City selectedCity;
    Models.Community selectedCommunity;


    public AppointmentPanel(JPanel bottomPanel, Models.Systems rootDataObj,  Models.City selectedCity, Models.Community selectedCommunity) {
        initComponents();
        this.bottomPanel = bottomPanel;
        this.rootDataObj = rootDataObj;
        this.selectedCity = selectedCity;
        this.selectedCommunity = selectedCommunity;
        populateDoctorTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctorsTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        goBackToLocationPanel = new javax.swing.JButton();

        jLabel1.setText("SELECT DOCTORS TO BOOK AN APPOINTMENT");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 412));

        doctorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "City", "Specialty", "YoE", "Qualifications"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        doctorsTable.setMinimumSize(new java.awt.Dimension(500, 80));
        doctorsTable.setPreferredSize(new java.awt.Dimension(500, 80));
        doctorsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doctorsTable);

        jButton1.setText("CONFIRM APPOINTMENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        goBackToLocationPanel.setText("GO BACK");
        goBackToLocationPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackToLocationPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goBackToLocationPanel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(447, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(goBackToLocationPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doctorsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorsTableMouseClicked
        // TODO add your handling code here:

        try{
            int selectedRowIndex = doctorsTable.getSelectedRow();
            if(selectedRowIndex < 0 ){

                throw new IllegalArgumentException("Select any one doctor profile");

            }
            else{
//                DefaultTableModel model = (DefaultTableModel) doctorTable.getModel();
//
//                firstNameTextField.setText(model.getValueAt(selectedRowIndex, 0).toString());
//                lastNameTextField.setText(model.getValueAt(selectedRowIndex, 1).toString());
//                cityTextField.setText(model.getValueAt(selectedRowIndex, 2).toString());
//                specialtyTextField.setText(model.getValueAt(selectedRowIndex, 3).toString());
//                yearofExperienceTextField.setText(model.getValueAt(selectedRowIndex, 4).toString());
//                qualificationTextField.setText(model.getValueAt(selectedRowIndex, 5).toString());

            }

        }
        catch (IllegalArgumentException e){

            JOptionPane.showMessageDialog(this, e.getMessage(),"Selection Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_doctorsTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Appointment Made Successfully!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void goBackToLocationPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackToLocationPanelActionPerformed
        // TODO add your handling code here:

        LocationPanel locationPanel = new LocationPanel(bottomPanel, this.rootDataObj);
        bottomPanel.add(locationPanel);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);
    }//GEN-LAST:event_goBackToLocationPanelActionPerformed

      private void populateDoctorTableData() {
        DefaultTableModel model = (DefaultTableModel) doctorsTable.getModel();
        model.setRowCount(0);
        DoctorDirectory doctorDirectory = new DoctorDirectory();
        
//        System.out.println("", this.rootDataObj.getRootHospitalDirectory());
        
        for(Hospital hospitalObj: this.rootDataObj.getRootHospitalDirectory()){
            if(hospitalObj.getCommunity().getCommunityName() == null ? selectedCommunity.getCommunityName() == null : hospitalObj.getCommunity().getCommunityName().equals(selectedCommunity.getCommunityName())) {
               doctorDirectory = hospitalObj.getDoctorsDirectory();
//               model.addRow(hospitalObj.getHospitalName());
            }
        }
        for (Doctor docObj: doctorDirectory.getDoctors()){
            Object[] row = new Object[6];

            row[0] = docObj.getFirstName();
            row[1] = docObj.getLastName();
            row[2] = docObj.getCity().getCityName();
            row[3] = docObj.getSpecialty();
            row[4] = docObj.getYearsOfExperiencce();
            row[5] = docObj.getQualifications();
            model.addRow(row);
        }
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable doctorsTable;
    private javax.swing.JButton goBackToLocationPanel;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
